# Generated by Django 4.0.3 on 2022-03-23 20:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "plate",
                    models.CharField(max_length=8, verbose_name="Plate"),
                ),
                (
                    "time",
                    models.DurationField(
                        default=datetime.timedelta(0), verbose_name="Time"
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(default=False, verbose_name="Paid"),
                ),
                (
                    "left",
                    models.BooleanField(default=False, verbose_name="Left"),
                ),
            ],
            options={
                "db_table": "parking",
            },
        ),
    ]
